CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32) NOT NULL,
    email VARCHAR(32) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32) NOT NULL,
    description varchar(64),
    available boolean,
    owner_id int REFERENCES users(id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   start_date  TIMESTAMP WITHOUT TIME ZONE,
   end_date  TIMESTAMP WITHOUT TIME ZONE,
   item_id int REFERENCES items(id),
   booker_id int REFERENCES users(id),
   status varchar(8),
   CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     text varchar(255) NOT NULL,
     item_id int REFERENCES items(id),
     author_id int REFERENCES users(id),
     created TIMESTAMP WITHOUT TIME ZONE,
     PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     description varchar(255),
     requestor_id int REFERENCES users(id),
     created TIMESTAMP WITHOUT TIME ZONE,
     PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS responses (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     request_id int REFERENCES requests(id),
     item_id int REFERENCES items(id),
     owner_id int REFERENCES users(id),
     created TIMESTAMP WITHOUT TIME ZONE,
     PRIMARY KEY (id)
);